### ISSUE TITLE
Веб-интерфейс

### ISSUE THREAD

**Issue by se4en** [DenisRogozhin/Slack-open-data-science-search-system#3]
Необходимо сделать веб-интерфейс для приложения, который в последствии будет доступен на localhost. В настоящий момент предполагается, что будет две основные страницы:

1. Основная страница, которая содержит поле для ввода поискового запроса и список результатов поиска.

2. Страница для показа результата поиска (т.е. непосредственно содержимого поста и комментариев к нему), переход на которую будет осуществляться при нажатии на один из результатов поиска. Также должна присутствовать возможность вернуться на основную страницу с результатами поиска.

Предполагается для реализации использовать библиотеку [streamlit](https://github.com/streamlit/streamlit).

**Comment by se4en** [comment]
Есть [плагин](https://github.com/m-wrzr/streamlit-searchbox#overview) для streamlit, чтобы реализовать собственный autocomplete.

**Comment by se4en** [comment]
- [ ] Сделать код более поддерживаемым, перенеся отображение различных элементов в классы
- [ ] Добавить базовое "красивое" отображение поста с комментариями на второй странице -- должно присутствовать непосредственно содержимое поста и комментариев, а также информация об авторах
- [ ] Добавить базовое "красивое" отображение постов в выдаче результатов поиска
- [ ] Добавить выбор кол-ва результат на одной и странице и возможность перемещения между страницами результатов

**Comment by se4en** [comment]
- [ ] Добавить локализацию

**Comment by DenisRogozhin** [comment]
Вмерджил, но надо добавить докстринге + прогнать код через pydocstyle
Также по этой части нужны:
1) локализация (#6)
2) тесты (#5)

**Comment by se4en** [comment]
Про доки: https://github.com/DenisRogozhin/Slack-open-data-science-search-system/issues/9
